---
title: "Florida Arrest Data"
output: 
    flexdashboard::flex_dashboard:
            orientation: rows
            self_contained: TRUE
---

```{r setup, include=FALSE}
library(dplyr)
library(here)
library(readr)
library(ggplot2)
library(DT)
library(plotly)
library(leaflet)

knitr::opts_chunk$set(echo = FALSE)

flordia_arrests1 = read_csv(here("data","FloridaConvictions","FloridaConvictions_00000.csv"))
arrest_data = flordia_arrests1 %>%
    mutate(ARREST_YEAR = as.character(ARREST_YEAR))

fl_counties_geo = tigris::counties(state = "12", year = "2024")

fl_county_pop = read.csv("https://www2.census.gov/programs-surveys/popest/datasets/2020-2023/counties/asrh/cc-est2023-agesex-12.csv")

fl_county_pop_sub = fl_county_pop %>%
    filter(YEAR == 1) %>%
    select(CTYNAME, POPESTIMATE)
    
fl_counties_geo = fl_counties_geo %>% left_join(fl_county_pop_sub, by = c("NAMELSAD"= "CTYNAME"))

createTabData = function(arrest_data, selected_grouping, selected_outcome, daterange,
                         remove_missing = FALSE, add_percent_column = FALSE,
                         use_suppression = TRUE){

    if(selected_grouping != "no_grouping"){
        
        out = arrest_data %>% 
            filter(ARREST_DATE >= daterange[1] & ARREST_DATE <= daterange[2]) %>%
            group_by( .data[[selected_outcome]], .data[[selected_grouping]] ) %>%
            summarize(count = n())
    }else{
        
        out = arrest_data %>% 
            filter(ARREST_DATE >= daterange[1] & ARREST_DATE <= daterange[2]) %>%
            group_by( .data[[selected_outcome]] ) %>%
            summarize(count = n()) %>%
            arrange(desc(count))
    }
    
    if(remove_missing){
        out = out %>% filter(! is.na(.data[[selected_outcome]]))
    }
    
    if(add_percent_column){
        
        if(selected_grouping != "no_grouping"){
            
            out = out %>%
                group_by(.data[[selected_grouping]]) %>%
                mutate(percent = 100*round(count/sum(count),4))
            
        }else{
            out = out %>%
                mutate(percent = 100*round(count/sum(count),4))
        }
    }

    #suppression criteria
    if(use_suppression){
        out = out %>% filter(count >= 10)
    }

    return(out)
}
```
# Data Analysis

## Table

```{r, degree_by_sex}

degree_by_sex = createTabData(arrest_data = arrest_data, selected_grouping = "SEX",
                         selected_outcome = "PROS_DEGREE",
                         daterange = c("2014-01-01", "2018-12-31"),
                         remove_missing = FALSE, add_percent_column = FALSE,
                         use_suppression = FALSE) %>%
                         arrange(count)

degree_by_sex %>% datatable(rownames = FALSE,
                          caption = "Arrest Degree by Sex",
                          extensions = c('Buttons'),
                          options = list(
                              paging = TRUE,
                              dom = 'Bfrtip',
                              buttons = c('colvis','csv', 'excel', 'pdf', 'print')
                          )
                )
```

## Plot and Commentary

### Plot

```{r}
plot_ly(degree_by_sex, x = ~PROS_DEGREE, y = ~count,
                             split = ~SEX, type = "bar")
```

### Analysis

Here is some commentary about the plot

# Map

##

### Map of 3rd Degree Prosecutions by County

```{r}
all_outcomes = arrest_data %>% 
    group_by(COUNTY) %>%
    summarize(count_var = sum(PROS_DEGREE %in% c("3rd Degree"),na.rm = TRUE))
        
map_data  = fl_counties_geo %>%
     left_join(all_outcomes, by = c(NAMELSAD = "COUNTY")) %>%
     mutate("count_var_rate_per_10k"= count_var / (POPESTIMATE/10000))

colors_for_palette = c("#EBF6FF","#6BAED6", "#08306B")
cont_pal = colorNumeric(colors_for_palette, domain = map_data$count_var_rate_per_10k, na.color = "#f1f1e0")

map_continous_scale = leaflet() %>%
    addProviderTiles(providers$Esri.WorldGrayCanvas) %>% #this is a more plain tile layer
    addPolygons(data =  map_data,
                color = "black", #controls the color of the shape boundaries
                weight = 2, #conrtrols the thickness of the shape boundaries
                fillOpacity = 1, #controls the opacity of the fill color
                fillColor = cont_pal(map_data$count_var_rate_per_10k),
                label = ~NAMELSAD) %>% #label gives the tooltip/hover label
    addLegend("bottomright",
                pal = cont_pal,
                title = "3rd Degree Arrests<br>per 10k persons",
                values = map_data$count_var_rate_per_10k,
                na.label = paste("No Estimate Available"),
                opacity = 1)  

map_continous_scale

```

